blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/ovenirdev/ovenir/discussions
    about: Ask questions and discuss ideas
  - name: ğŸ“– Documentation
    url: https://ovenir.com/docs
    about: Read the documentation
